firstname = str(input("What is your firstname?\n"))
surname = str(input("What is your surname?\n"))
dob = str(input("What is your date of birth?\n"))
print("What is your address?")
house_num = str(input("- House number: "))
street = str(input("- Street name: "))
city = str(input("- City/town: "))
postcode = str(input("- Postcode: "))
hobbies = str(input("What are your hobbies?\n"))

# print(type(firstname) == str)
# print(type(surname) == str)
# print(type(dob) == str)
# print(type(house_num) == str)
# print(type(street) == str)
# print(type(city) == str)
# print(type(postcode) == str)
# print(type(hobbies) == str)

print("Firstname: " + firstname)
print("Surname: " + surname)
print("DOB: " + dob)
print(f"Address: {house_num} {street}, {city}, {postcode}")
print("Hobbies: " + hobbies)
